name: Deploy via FTP
 
on:
  push:
    branches:
      - main   # případně uprav na jinou větev
 
jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
 
    steps:
      # 1️⃣ Checkout repozitáře
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # 2️⃣  Deploy přes FTP
      - name: Deploy to FTP server
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
 
          local_source_dir: "ulohy/"
          dist_target_dir: "web/"
 
          delete: "true"
          exclude: "'^logs/' '^README.md'
